from api import acad_dll
from stubs import *
from app import AcadApplication
from objects import *
from geometry import *
from doc import AcadDatabase, AcadDocument, AcadDocuments
from blocks import (
    AcadBlock,
    AcadModelSpace,
    AcadPaperSpace,
    AcadBlocks,
)

_dll = acad_dll.dll

dict_cast = {
    #AcadComparedReference: POINTER(_dll.IAcadComparedReference),
    #AcadObjectEvents: POINTER(_dll.IAcadObjectEvents), Event interface class
    Acad3DFace: POINTER(_dll.IAcad3DFace),
    Acad3DPolyline: POINTER(_dll.IAcad3DPolyline),
    Acad3DSolid: POINTER(_dll.IAcad3DSolid),
    AcadAcCmColor: POINTER(_dll.IAcadAcCmColor),
    AcadApplication: POINTER(_dll.IAcadApplication),
    AcadArc: POINTER(_dll.IAcadArc),
    AcadAttribute: POINTER(_dll.IAcadAttribute),
    AcadAttributeReference: POINTER(_dll.IAcadAttributeReference),
    AcadBlock: POINTER(_dll.IAcadBlock),
    AcadBlockReference: POINTER(_dll.IAcadBlockReference),
    AcadBlocks: POINTER(_dll.IAcadBlocks),
    AcadCircle: POINTER(_dll.IAcadCircle),
    AcadDatabase: POINTER(_dll.IAcadDatabase),
    AcadDatabasePreferences: POINTER(_dll.IAcadDatabasePreferences),
    AcadDgnUnderlay: POINTER(_dll.AcadDgnUnderlay),
    AcadDictionaries: POINTER(_dll.IAcadDictionaries),
    AcadDictionary: POINTER(_dll.IAcadDictionary),
    AcadDim3PointAngular: POINTER(_dll.IAcadDim3PointAngular),
    AcadDimAligned: POINTER(_dll.IAcadDimAligned),
    AcadDimAngular: POINTER(_dll.IAcadDimAngular),
    AcadDimArcLength: POINTER(_dll.IAcadDimArcLength),
    AcadDimDiametric: POINTER(_dll.IAcadDimDiametric),
    AcadDimOrdinate: POINTER(_dll.IAcadDimOrdinate),
    AcadDimRadial: POINTER(_dll.IAcadDimRadial),
    AcadDimRadialLarge: POINTER(_dll.IAcadDimRadialLarge),
    AcadDimRotated: POINTER(_dll.IAcadDimRotated),
    AcadDimStyle: POINTER(_dll.IAcadDimStyle),
    AcadDimStyles: POINTER(_dll.IAcadDimStyles),
    AcadDimension: POINTER(_dll.IAcadDimension),
    AcadDocument: POINTER(_dll.IAcadDocument),
    AcadDocuments: POINTER(_dll.IAcadDocuments),
    AcadDwfUnderlay: POINTER(_dll.IAcadDwfUnderlay),
    AcadDynamicBlockReferenceProperty: POINTER(_dll.IAcadDynamicBlockReferenceProperty),
    AcadEllipse: POINTER(_dll.IAcadEllipse),
    AcadEntity: POINTER(_dll.IAcadEntity),
    AcadExternalReference: POINTER(_dll.IAcadExternalReference),
    AcadExtrudedSurface: POINTER(_dll.IAcadExtrudedSurface),
    AcadGeoPositionMarker: POINTER(_dll.IAcadGeoPositionMarker),
    AcadGroup: POINTER(_dll.IAcadGroup),
    AcadGroups: POINTER(_dll.IAcadGroups),
    AcadHatch: POINTER(_dll.IAcadHatch),
    AcadHelix: POINTER(_dll.IAcadHelix),
    AcadHyperlink: POINTER(_dll.IAcadHyperlink),
    AcadHyperlinks: POINTER(_dll.IAcadHyperlinks),
    AcadIdPair: POINTER(_dll.IAcadIdPair),
    AcadLWPolyline: POINTER(_dll.IAcadLWPolyline),
    AcadLayer: POINTER(_dll.IAcadLayer),
    AcadLayerStateManager: POINTER(_dll.IAcadLayerStateManager),
    AcadLayers: POINTER(_dll.IAcadLayers),
    AcadLayout: POINTER(_dll.IAcadLayout),
    AcadLayouts: POINTER(_dll.IAcadLayouts),
    AcadLeader: POINTER(_dll.IAcadLeader),
    AcadLine: POINTER(_dll.IAcadLine),
    AcadLineType: POINTER(_dll.IAcadLineType),
    AcadLineTypes: POINTER(_dll.IAcadLineTypes),
    AcadLoftedSurface: POINTER(_dll.IAcadLoftedSurface),
    AcadMInsertBlock: POINTER(_dll.IAcadMInsertBlock),
    AcadMLeader: POINTER(_dll.IAcadMLeader),
    AcadMLeaderLeader: POINTER(_dll.IAcadMLeaderLeader),
    AcadMLeaderStyle: POINTER(_dll.IAcadMLeaderStyle),
    AcadMLine: POINTER(_dll.IAcadMLine),
    AcadMText: POINTER(_dll.IAcadMText),
    AcadMaterial: POINTER(_dll.IAcadMaterial),
    AcadMaterials: POINTER(_dll.IAcadMaterials),
    AcadMenuBar: POINTER(_dll.IAcadMenuBar),
    AcadMenuGroup: POINTER(_dll.IAcadMenuGroup),
    AcadMenuGroups: POINTER(_dll.IAcadMenuGroups),
    AcadModelSpace: POINTER(_dll.IAcadModelSpace),
    AcadNurbSurface: POINTER(_dll.IAcadNurbSurface),
    AcadObject: POINTER(_dll.IAcadObject),
    AcadOle: POINTER(_dll.IAcadOle),
    AcadPViewport: POINTER(_dll.IAcadPViewport),
    AcadPaperSpace: POINTER(_dll.IAcadPaperSpace),
    AcadPdfUnderlay: POINTER(_dll.AcadPdfUnderlay),
    AcadPlaneSurface: POINTER(_dll.IAcadPlaneSurface),
    AcadPlot: POINTER(_dll.IAcadPlot),
    AcadPlotConfiguration: POINTER(_dll.IAcadPlotConfiguration),
    AcadPlotConfigurations: POINTER(_dll.IAcadPlotConfigurations),
    AcadPoint: POINTER(_dll.IAcadPoint),
    AcadPointCloud: POINTER(_dll.IAcadPointCloud),
    AcadPointCloudEx: POINTER(_dll.IAcadPointCloudEx),
    AcadPolyfaceMesh: POINTER(_dll.IAcadPolyfaceMesh),
    AcadPolygonMesh: POINTER(_dll.IAcadPolygonMesh),
    AcadPolyline: POINTER(_dll.IAcadPolyline),
    AcadPopupMenu: POINTER(_dll.IAcadPopupMenu),
    AcadPopupMenuItem: POINTER(_dll.IAcadPopupMenuItem),
    AcadPopupMenus: POINTER(_dll.IAcadPopupMenus),
    AcadPreferences: POINTER(_dll.IAcadPreferences),
    AcadPreferencesDisplay: POINTER(_dll.IAcadPreferencesDisplay),
    AcadPreferencesDrafting: POINTER(_dll.IAcadPreferencesDrafting),
    AcadPreferencesFiles: POINTER(_dll.IAcadPreferencesFiles),
    AcadPreferencesOpenSave: POINTER(_dll.IAcadPreferencesOpenSave),
    AcadPreferencesOutput: POINTER(_dll.IAcadPreferencesOutput),
    AcadPreferencesProfiles: POINTER(_dll.IAcadPreferencesProfiles),
    AcadPreferencesSelection: POINTER(_dll.IAcadPreferencesSelection),
    AcadPreferencesSystem: POINTER(_dll.IAcadPreferencesSystem),
    AcadPreferencesUser: POINTER(_dll.IAcadPreferencesUser),
    AcadRasterImage: POINTER(_dll.IAcadRasterImage),
    AcadRay: POINTER(_dll.IAcadRay),
    AcadRegion: POINTER(_dll.IAcadRegion),
    AcadRegisteredApplication: POINTER(_dll.IAcadRegisteredApplication),
    AcadRegisteredApplications: POINTER(_dll.IAcadRegisteredApplications),
    AcadRevolvedSurface: POINTER(_dll.IAcadRevolvedSurface),
    AcadSection: POINTER(_dll.IAcadSection),
    AcadSectionManager: POINTER(_dll.IAcadSectionManager),
    AcadSectionSettings: POINTER(_dll.IAcadSectionSettings),
    AcadSectionTypeSettings: POINTER(_dll.IAcadSectionTypeSettings),
    AcadSecurityParams: POINTER(_dll.IAcadSecurityParams),
    AcadSelectionSet: POINTER(_dll.IAcadSelectionSet),
    AcadSelectionSets: POINTER(_dll.IAcadSelectionSets),
    AcadShape: POINTER(_dll.IAcadShape),
    AcadSolid: POINTER(_dll.IAcadSolid),
    AcadSortentsTable: POINTER(_dll.IAcadSortentsTable),
    AcadSpline: POINTER(_dll.IAcadSpline),
    AcadState: POINTER(_dll.IAcadState),
    AcadSubDMesh: POINTER(_dll.IAcadSubDMesh),
    AcadSubDMeshEdge: POINTER(_dll.IAcadSubDMeshEdge),
    AcadSubDMeshFace: POINTER(_dll.IAcadSubDMeshFace),
    AcadSubDMeshVertex: POINTER(_dll.IAcadSubDMeshVertex),
    AcadSubEntSolidEdge: POINTER(_dll.IAcadSubEntSolidEdge),
    AcadSubEntSolidFace: POINTER(_dll.IAcadSubEntSolidFace),
    AcadSubEntSolidNode: POINTER(_dll.IAcadSubEntSolidNode),
    AcadSubEntSolidVertex: POINTER(_dll.IAcadSubEntSolidVertex),
    AcadSubEntity: POINTER(_dll.IAcadSubEntity),
    AcadSummaryInfo: POINTER(_dll.IAcadSummaryInfo),
    AcadSurface: POINTER(_dll.IAcadSurface),
    AcadSweptSurface: POINTER(_dll.IAcadSweptSurface),
    AcadTable: POINTER(_dll.IAcadTable),
    AcadTableStyle: POINTER(_dll.IAcadTableStyle),
    AcadText: POINTER(_dll.IAcadText),
    AcadTextStyle: POINTER(_dll.IAcadTextStyle),
    AcadTextStyles: POINTER(_dll.IAcadTextStyles),
    AcadTolerance: POINTER(_dll.IAcadTolerance),
    AcadToolbar: POINTER(_dll.IAcadToolbar),
    AcadToolbarItem: POINTER(_dll.IAcadToolbarItem),
    AcadToolbars: POINTER(_dll.IAcadToolbars),
    AcadTrace: POINTER(_dll.IAcadTrace),
    AcadUCS: POINTER(_dll.IAcadUCS),
    AcadUCSs: POINTER(_dll.IAcadUCSs),
    AcadUnderlay: POINTER(_dll.IAcadUnderlay),
    AcadUtility: POINTER(_dll.IAcadUtility),
    AcadView: POINTER(_dll.IAcadView),
    AcadViewport: POINTER(_dll.IAcadViewport),
    AcadViewports: POINTER(_dll.IAcadViewports),
    AcadViews: POINTER(_dll.IAcadViews),
    AcadWipeout: POINTER(_dll.IAcadWipeout),
    AcadXRecord: POINTER(_dll.IAcadXRecord),
    AcadXline: POINTER(_dll.IAcadXline),
}

dict_cast2 = {
    POINTER(_dll.IAcad3DFace).__name__: Acad3DFace,
    POINTER(_dll.IAcad3DPolyline).__name__: Acad3DPolyline,
    POINTER(_dll.IAcad3DSolid).__name__: Acad3DSolid,
    POINTER(_dll.IAcadAcCmColor).__name__: AcadAcCmColor,
    POINTER(_dll.IAcadApplication).__name__: AcadApplication,
    POINTER(_dll.IAcadArc).__name__: AcadArc,
    POINTER(_dll.IAcadAttribute).__name__: AcadAttribute,
    POINTER(_dll.IAcadAttributeReference).__name__: AcadAttributeReference,
    POINTER(_dll.IAcadBlock).__name__: AcadBlock,
    POINTER(_dll.IAcadBlockReference).__name__: AcadBlockReference,
    POINTER(_dll.IAcadBlocks).__name__: AcadBlocks,
    POINTER(_dll.IAcadCircle).__name__: AcadCircle,
    #POINTER(_dll.IAcadComparedReference).__name__: AcadComparedReference,
    POINTER(_dll.IAcadDatabase).__name__: AcadDatabase,
    POINTER(_dll.IAcadDatabasePreferences).__name__: AcadDatabasePreferences,
    POINTER(_dll.AcadDgnUnderlay).__name__: AcadDgnUnderlay,
    POINTER(_dll.IAcadDictionaries).__name__: AcadDictionaries,
    POINTER(_dll.IAcadDictionary).__name__: AcadDictionary,
    POINTER(_dll.IAcadDim3PointAngular).__name__: AcadDim3PointAngular,
    POINTER(_dll.IAcadDimAligned).__name__: AcadDimAligned,
    POINTER(_dll.IAcadDimAngular).__name__: AcadDimAngular,
    POINTER(_dll.IAcadDimArcLength).__name__: AcadDimArcLength,
    POINTER(_dll.IAcadDimDiametric).__name__: AcadDimDiametric,
    POINTER(_dll.IAcadDimOrdinate).__name__: AcadDimOrdinate,
    POINTER(_dll.IAcadDimRadial).__name__: AcadDimRadial,
    POINTER(_dll.IAcadDimRadialLarge).__name__: AcadDimRadialLarge,
    POINTER(_dll.IAcadDimRotated).__name__: AcadDimRotated,
    POINTER(_dll.IAcadDimStyle).__name__: AcadDimStyle,
    POINTER(_dll.IAcadDimStyles).__name__: AcadDimStyles,
    POINTER(_dll.IAcadDimension).__name__: AcadDimension,
    POINTER(_dll.IAcadDocument).__name__: AcadDocument,
    POINTER(_dll.IAcadDocuments).__name__: AcadDocuments,
    POINTER(_dll.IAcadDwfUnderlay).__name__: AcadDwfUnderlay,
    POINTER(_dll.IAcadDynamicBlockReferenceProperty).__name__: AcadDynamicBlockReferenceProperty,
    POINTER(_dll.IAcadEllipse).__name__: AcadEllipse,
    POINTER(_dll.IAcadEntity).__name__: AcadEntity,
    POINTER(_dll.IAcadExternalReference).__name__: AcadExternalReference,
    POINTER(_dll.IAcadExtrudedSurface).__name__: AcadExtrudedSurface,
    POINTER(_dll.IAcadGeoPositionMarker).__name__: AcadGeoPositionMarker,
    POINTER(_dll.IAcadGroup).__name__: AcadGroup,
    POINTER(_dll.IAcadGroups).__name__: AcadGroups,
    POINTER(_dll.IAcadHatch).__name__: AcadHatch,
    POINTER(_dll.IAcadHelix).__name__: AcadHelix,
    POINTER(_dll.IAcadHyperlink).__name__: AcadHyperlink,
    POINTER(_dll.IAcadHyperlinks).__name__: AcadHyperlinks,
    POINTER(_dll.IAcadIdPair).__name__: AcadIdPair,
    POINTER(_dll.IAcadLWPolyline).__name__: AcadLWPolyline,
    POINTER(_dll.IAcadLayer).__name__: AcadLayer,
    POINTER(_dll.IAcadLayerStateManager).__name__: AcadLayerStateManager,
    POINTER(_dll.IAcadLayers).__name__: AcadLayers,
    POINTER(_dll.IAcadLayout).__name__: AcadLayout,
    POINTER(_dll.IAcadLayouts).__name__: AcadLayouts,
    POINTER(_dll.IAcadLeader).__name__: AcadLeader,
    POINTER(_dll.IAcadLine).__name__: AcadLine,
    POINTER(_dll.IAcadLineTypes).__name__: AcadLineTypes,
    POINTER(_dll.IAcadLineType).__name__: AcadLineType,
    POINTER(_dll.IAcadLoftedSurface).__name__: AcadLoftedSurface,
    POINTER(_dll.IAcadMInsertBlock).__name__: AcadMInsertBlock,
    POINTER(_dll.IAcadMLeader).__name__: AcadMLeader,
    POINTER(_dll.IAcadMLeaderLeader).__name__: AcadMLeaderLeader,
    POINTER(_dll.IAcadMLeaderStyle).__name__: AcadMLeaderStyle,
    POINTER(_dll.IAcadMLine).__name__: AcadMLine,
    POINTER(_dll.IAcadMaterial).__name__: AcadMaterial,
    POINTER(_dll.IAcadMaterials).__name__: AcadMaterials,
    POINTER(_dll.IAcadMenuBar).__name__: AcadMenuBar,
    POINTER(_dll.IAcadMenuGroup).__name__: AcadMenuGroup,
    POINTER(_dll.IAcadMenuGroups).__name__: AcadMenuGroups,
    POINTER(_dll.IAcadModelSpace).__name__: AcadModelSpace,
    POINTER(_dll.IAcadMText).__name__: AcadMText,
    POINTER(_dll.IAcadNurbSurface).__name__: AcadNurbSurface,
    POINTER(_dll.IAcadObject).__name__: AcadObject,
    #POINTER(_dll.IAcadObjectEvents).__name__: AcadObjectEvents,
    POINTER(_dll.IAcadOle).__name__: AcadOle,
    POINTER(_dll.IAcadPViewport).__name__: AcadPViewport,
    POINTER(_dll.IAcadPaperSpace).__name__: AcadPaperSpace,
    POINTER(_dll.AcadPdfUnderlay).__name__: AcadPdfUnderlay,
    POINTER(_dll.IAcadPlaneSurface).__name__: AcadPlaneSurface,
    POINTER(_dll.IAcadPlot).__name__: AcadPlot,
    POINTER(_dll.IAcadPlotConfiguration).__name__: AcadPlotConfiguration,
    POINTER(_dll.IAcadPlotConfigurations).__name__: AcadPlotConfigurations,
    POINTER(_dll.IAcadPoint).__name__: AcadPoint,
    POINTER(_dll.IAcadPointCloud).__name__: AcadPointCloud,
    POINTER(_dll.IAcadPointCloudEx).__name__: AcadPointCloudEx,
    POINTER(_dll.IAcadPolyfaceMesh).__name__: AcadPolyfaceMesh,
    POINTER(_dll.IAcadPolygonMesh).__name__: AcadPolygonMesh,
    POINTER(_dll.IAcadPolyline).__name__: AcadPolyline,
    POINTER(_dll.IAcadPopupMenu).__name__: AcadPopupMenu,
    POINTER(_dll.IAcadPopupMenuItem).__name__: AcadPopupMenuItem,
    POINTER(_dll.IAcadPopupMenus).__name__: AcadPopupMenus,
    POINTER(_dll.IAcadPreferences).__name__: AcadPreferences,
    POINTER(_dll.IAcadPreferencesDisplay).__name__: AcadPreferencesDisplay,
    POINTER(_dll.IAcadPreferencesDrafting).__name__: AcadPreferencesDrafting,
    POINTER(_dll.IAcadPreferencesFiles).__name__: AcadPreferencesFiles,
    POINTER(_dll.IAcadPreferencesOpenSave).__name__: AcadPreferencesOpenSave,
    POINTER(_dll.IAcadPreferencesOutput).__name__: AcadPreferencesOutput,
    POINTER(_dll.IAcadPreferencesProfiles).__name__: AcadPreferencesProfiles,
    POINTER(_dll.IAcadPreferencesSelection).__name__: AcadPreferencesSelection,
    POINTER(_dll.IAcadPreferencesSystem).__name__: AcadPreferencesSystem,
    POINTER(_dll.IAcadPreferencesUser).__name__: AcadPreferencesUser,
    POINTER(_dll.IAcadRasterImage).__name__: AcadRasterImage,
    POINTER(_dll.IAcadRay).__name__: AcadRay,
    POINTER(_dll.IAcadRegion).__name__: AcadRegion,
    POINTER(_dll.IAcadRegisteredApplication).__name__: AcadRegisteredApplication,
    POINTER(_dll.IAcadRegisteredApplications).__name__: AcadRegisteredApplications,
    POINTER(_dll.IAcadRevolvedSurface).__name__: AcadRevolvedSurface,
    POINTER(_dll.IAcadSection).__name__: AcadSection,
    POINTER(_dll.IAcadSectionManager).__name__: AcadSectionManager,
    POINTER(_dll.IAcadSectionSettings).__name__: AcadSectionSettings,
    POINTER(_dll.IAcadSectionTypeSettings).__name__: AcadSectionTypeSettings,
    POINTER(_dll.IAcadSecurityParams).__name__: AcadSecurityParams,
    POINTER(_dll.IAcadSelectionSet).__name__: AcadSelectionSet,
    POINTER(_dll.IAcadSelectionSets).__name__: AcadSelectionSets,
    POINTER(_dll.IAcadShape).__name__: AcadShape,
    POINTER(_dll.IAcadSolid).__name__: AcadSolid,
    POINTER(_dll.IAcadSortentsTable).__name__: AcadSortentsTable,
    POINTER(_dll.IAcadSpline).__name__: AcadSpline,
    POINTER(_dll.IAcadState).__name__: AcadState,
    POINTER(_dll.IAcadSubDMesh).__name__: AcadSubDMesh,
    POINTER(_dll.IAcadSubDMeshEdge).__name__: AcadSubDMeshEdge,
    POINTER(_dll.IAcadSubDMeshFace).__name__: AcadSubDMeshFace,
    POINTER(_dll.IAcadSubDMeshVertex).__name__: AcadSubDMeshVertex,
    POINTER(_dll.IAcadSubEntSolidEdge).__name__: AcadSubEntSolidEdge,
    POINTER(_dll.IAcadSubEntSolidFace).__name__: AcadSubEntSolidFace,
    POINTER(_dll.IAcadSubEntSolidNode).__name__: AcadSubEntSolidNode,
    POINTER(_dll.IAcadSubEntSolidVertex).__name__: AcadSubEntSolidVertex,
    POINTER(_dll.IAcadSubEntity).__name__: AcadSubEntity,
    POINTER(_dll.IAcadSummaryInfo).__name__: AcadSummaryInfo,
    POINTER(_dll.IAcadSurface).__name__: AcadSurface,
    POINTER(_dll.IAcadSweptSurface).__name__: AcadSweptSurface,
    POINTER(_dll.IAcadTable).__name__: AcadTable,
    POINTER(_dll.IAcadTableStyle).__name__: AcadTableStyle,
    POINTER(_dll.IAcadText).__name__: AcadText,
    POINTER(_dll.IAcadTextStyle).__name__: AcadTextStyle,
    POINTER(_dll.IAcadTextStyles).__name__: AcadTextStyles,
    POINTER(_dll.IAcadTolerance).__name__: AcadTolerance,
    POINTER(_dll.IAcadToolbar).__name__: AcadToolbar,
    POINTER(_dll.IAcadToolbarItem).__name__: AcadToolbarItem,
    POINTER(_dll.IAcadToolbars).__name__: AcadToolbars,
    POINTER(_dll.IAcadTrace).__name__: AcadTrace,
    POINTER(_dll.IAcadUCS).__name__: AcadUCS,
    POINTER(_dll.IAcadUCSs).__name__: AcadUCSs,
    POINTER(_dll.IAcadUnderlay).__name__: AcadUnderlay,
    POINTER(_dll.IAcadUtility).__name__: AcadUtility,
    POINTER(_dll.IAcadView).__name__: AcadView,
    POINTER(_dll.IAcadViewport).__name__: AcadViewport,
    POINTER(_dll.IAcadViewports).__name__: AcadViewports,
    POINTER(_dll.IAcadViews).__name__: AcadViews,
    POINTER(_dll.IAcadWipeout).__name__: AcadWipeout,
    POINTER(_dll.IAcadXRecord).__name__: AcadXRecord,
    POINTER(_dll.IAcadXline).__name__: AcadXline
}

'''
dict_ObjectName = {
    'AcDbFace': Acad3DFace,
    'AcDb3dPolyline': Acad3DPolyline,
    'AcDb3dSolid': Acad3DSolid,
    'AcDbArc': AcadArc,
    'AcDbAttributeDefinition': AcadAttribute,
    'AcDbAttribute': AcadAttributeReference,
    'AcDbBlockReference': AcadBlockReference,
    'AcDbBlockTable': AcadBlocks,
    'AcDbCircle': AcadCircle,
    'AcDb3PointAngularDimension': AcadDim3PointAngular,
    'AcDbAlignedDimension': AcadDimAligned,
    'AcDb2LineAngularDimension': AcadDimAngular,
    'AcDbArcDimension': AcadDimArcLength,
    'AcDbDiametricDimension': AcadDimDiametric,
    'AcDbOrdinateDimension': AcadDimOrdinate,
    'AcDbRadialDimension': AcadDimRadial,
    'AcDbRadialDimensionLarge': AcadDimRadialLarge,
    'AcDbRotatedDimension': AcadDimRotated,
    'AcDbDimStyleTableRecord': AcadDimStyle,
    'AcDbDimStyleTable': AcadDimStyles,
    'AcDbEllipse': AcadEllipse,
    'AcDbGroup': AcadGroup,
    'AcDbHatch': AcadHatch,
    'AcDbHelix': AcadHelix,
    'AcDbPolyline': AcadLWPolyline,
    'AcDbLayerTableRecord': AcadLayer,
    'AcDbLayerTable': AcadLayers,
    'AcDbLayout': AcadLayout,
    'AcDbLine': AcadLine,
    'AcDbMInsertBlock': AcadMInsertBlock,
    'AcDbMLeader': AcadMLeader,
    'AcDbMaterial': AcadMaterial,
    'AcDbMText': AcadMText,
    'AcDbPlotSettings': AcadPlotConfiguration,
    'AcDbPoint': AcadPoint,
    'AcDbRay': AcadRay,
    'AcDbRegion': AcadRegion,
    'AcDbRegAppTableRecord': AcadRegisteredApplication,
    'AcDbRegAppTable': AcadRegisteredApplications,
    'AcDbSectionManager': AcadSectionManager,
    'AcDbSectionSettings': AcadSectionSettings,
    'AcDbSpline': AcadSpline,
    'AcDbText': AcadText,
    'AcDbTextStyleTableRecord': AcadTextStyle,
    'AcDbTextStyleTable': AcadTextStyles,
    'AcDbWipeout': AcadWipeout,
    'AcDbXrecord': AcadXRecord,
    'AcDbXline': AcadXline,
}

dict_ON_intersections = {
    AcadBlock: 'AcDbBlockTableRecord' # !!!,
    AcadDictionaries: 'AcDbDictionary',
    AcadDictionary: 'AcDbDictionary',
    AcadExternalReference: 'AcDbBlockReference',
    AcadGroups: 'AcDbDictionary',
    AcadLayouts: 'AcDbDictionary',
    AcadMaterials: 'AcDbDictionary',
    AcadModelSpace: 'AcDbBlockTableRecord',
    AcadPaperSpace: 'AcDbBlockTableRecord',
    AcadPlotConfigurations: 'AcDbDictionary',
    AcadSection: 'AcDbSection',
    AcadSection2: 'AcDbSection',
    CLASS: 'Name',
    CLASS: 'Name',
    CLASS: 'Name',
    CLASS: 'Name',
}
'''

'''
AcadComparedReference       (Not supported)
AcadDgnUnderlay             
AcadDimension               INTERFACE
AcadDwfUnderlay             
AcadEntity                  INTERFACE
AcadExtrudedSurface         
AcadGeoPositionMarker       TODO
AcadLeader                  ?????????
AcadLineTypes               
AcadLineType                
AcadLoftedSurface           
AcadMLeaderStyle            
AcadMLine                   
AcadNurbSurface             
AcadObject                  INTERFACE
AcadOle                     
AcadPViewport               
AcadPdfUnderlay             
AcadPlaneSurface             
AcadPointCloud              
AcadPointCloudEx            
AcadPolyfaceMesh            
AcadPolygonMesh             
AcadPolyline                
AcadRasterImage             
AcadRevolvedSurface         
AcadShape                   
AcadSolid                   
AcadSortentsTable           
AcadSubDMesh                
AcadSurface                 
AcadSweptSurface            
AcadTable                   
AcadTableStyle              
AcadTolerance               
AcadTrace                   
AcadUCS                     
AcadUCSs                    
AcadUnderlay                
AcadView                    
AcadViewport                
AcadViewports               
AcadViews                   

UNKNOWN                     AcDbDictionaryWithDefault
UNKNOWN                     AcDbRapidRTRenderSettings
UNKNOWN                     AcDbWipeoutVariables

'''

# for debugging
if __name__ == "__main__":
    pass
